### ISSUE TITLE
Video Example - recorded video replays too fast in VLC.

### ISSUE THREAD

**Issue by ch08532** [trilliumeng/orion-sdk#13]
I am replaying recorded video from an HD50 camera (captures via SkyLink) via ffmpeg to the video example application and everything seems to work as expected (video does record and metadata is parsed). However, when I attempt to replay the recorded file generated by the video example it is playing way to fast.  It's almost like the time scale values are not set right.  I'm using VLC to replay the recorded video.

using this command to send pre-recorded video to the example: ffmpeg -re  -i 13_46_29.ts -map 0 -c copy -f mpegts udp://192.168.113.170:15004

Note that I commented out the OrionCommOpen() function as I don't have a HD50 camera with me.  Just want to test the KLV decoding logic and recorder.

**Comment by jefffisher** [comment]
Hi @ch08532 – you might try the `-use_wallclock_as_timestamps 1` option for ffmpeg. I will also try to reproduce here.
