### ISSUE TITLE
Stream decoder computes wrong frame buffer size

### ISSUE THREAD

**Issue by sezekiel-insitu** [trilliumeng/orion-sdk#14]
Line 327 of the file StreamDecoder.c verifies that the buffer to hold a video frame is large enough.  It reads:
```c
if ((pFrameCopy->width > 0) && (pFrameCopy->height > 0) && ((pFrame->width * pFrame->height * 3) < MaxBytes))
```
I believe it should read:
```c
if ((pFrameCopy->width > 0) && (pFrameCopy->height > 0) && ((pFrameCopy->width * pFrameCopy->height * 3) <= MaxBytes))
```

**Comment by trilliumbuild** [comment]
Thank you for your help pinning this issue down the fix has been incorporated into the 24.1 release.
