### ISSUE TITLE
StreamDecoder.c using deprecated values

### ISSUE THREAD

**Issue by TheLumbee** [trilliumeng/orion-sdk#15]
AVStream no longer has a member named codec. I've found some examples of other who have ran into this issue like [here](https://lists.ffmpeg.org/pipermail/libav-user/2016-October/009801.html).

Apparently, codecpar is the updated member but unsure if it functions similarly.

**Comment by trilliumbuild** [comment]
This has been an ongoing issue and depends on the version of AVStream being used this is now fixed for the 24.1 release.
