### ISSUE TITLE
OrionCommOpenNetworkIp(...) appears to return true on failed connection attempt

### ISSUE THREAD

**Issue by ryanks12** [trilliumeng/orion-sdk#17]
From the naming, it looks like the intention of _OrionCommOpenNetworkIp(...)_ is to return whether a connection has successfully been established with a Trillium gimbal, but frequently I've found that this function will return true without a connection being established.

I understand that this function is just returning the socket status, but I think it would be better if it actually checked if there was a valid connection to a gimbal. For now it seems sending some dummy data (_using OrionCommSend(...)_) to the gimbal is the best way to check if you've connected to a gimbal.

Is this the desired behavior or am I using the SDK wrong?

**Comment by trilliumbuild** [comment]
You are correct.  This call just opens up the network to be able to talk with the gimbal.  At that point you would request data from the gimbal to verify that the rest of your network is working.
