### ISSUE TITLE
Video Player Issues 

### ISSUE THREAD

**Issue by jugpanther** [trilliumeng/orion-sdk#20]
First, it would be helpful to me and others to include an example launch command in the Readme. I have been running the videoplayer file with the configured IPs and port number. 

The system starts to capture frames, and the S and Q commands don't seem to work when running. Nothing happens and the Q command will not quit the application. 

Pointing to a folder location to save the captures causes a segment fault. Not sure why this is happening.

**Comment by gvnwltrs** [comment]
Looks like there was another while loop inside the forever while loop that was blocking the keyboard commands for the VideoPlayer source code. Pull request submitted.

**Comment by trilliumbuild** [comment]
Thanks for the feedback.  I think both of these fixes are incorporated in the 24.1 release.
