### ISSUE TITLE
Failure to make Communications but can make Utils

### ISSUE THREAD

**Issue by chababster** [trilliumeng/orion-sdk#23]
*RASPBIAN 10* 
**Platform**: Raspberry Pi running Raspbian 10 armv7l GNU/Linux
**Issue**: Unable to execute make successfully in Communications folder.
**Error** from running ```make``` in orion-sdk/Communications/: 
``` 
OrionPublicPacket.c: In function ‘decodeGeolocateTelemetryCorePacketStructure’:
OrionPublicPacket.c:563:28: error: incompatible types when assigning to type ‘PrimaryTrackData_t’ {aka ‘struct <anonymous>’} from type ‘int’
     user->primaryTrackData = 0;
                            ^
make: *** [Makefile:8: x86/obj/OrionPublicPacket.o] Error 1
```

** No issues when running ``` make ``` in orion-sdk/Utils/ directory

**Comment by chababster** [comment]
Commenting out line 563 in file ```./orion-sdk/Communications/OrionPublicPacket.c``` and re-running make solves this error.

**Comment by trilliumbuild** [comment]
Can you verify that you generated the code using [Protogen version 2.12.d](https://github.com/trilliumeng/ProtoGen/releases/tag/2.12.d_trillium)?  Later releases have not been validated and are likely to cause issues.
