### ISSUE TITLE
TrackSize Project build errors

### ISSUE THREAD

**Issue by jebjosh** [trilliumeng/orion-sdk#25]
![image](https://github.com/user-attachments/assets/1fdd5ff1-a49f-499d-9dcd-0a775a31133c)

I get this error when I build TrackSize. This is for version 24.1 orion-sdk

**Comment by trilliumbuild** [comment]
It looks like you might not have built or included the Communications library.  A top level project build may resolve the linker error which is trying to trying to statically link libOrionComm
