### ISSUE TITLE
VideoPlayer Makefile breaks cross-compilation builds due to override of build flags

### ISSUE THREAD

**Issue by John-Ingersoll** [trilliumeng/orion-sdk#4]
The Makefile for the video player contains:
```
LDFLAGS=-lavcodec -lavformat -lavutil -lswscale -ljpeg
CFLAGS=-D_GNU_SOURCE
```

This removes any commandline provided options for these variables.  This breaks the build process on cross-compilation systems.
The assignment should be an append not an override.

**Comment by jefffisher** [comment]
Done – see 381168e

**Comment by John-Ingersoll** [comment]
Thank you for the quick turn.  I was able to rebuild against this update
with fewer issues.

You may want to consider making the examples as a different make target so
that we can build the library without the examples from a clean clone.

**Comment by jefffisher** [comment]
I'd be happy to add that; alternatively, if you just want to rework the makefiles as you see fit and submit a pull request, that works for me too.
